### ISSUE TITLE
Buttons To-Do

### ISSUE THREAD

**Issue by natbibi** [natbibi/LAP-1-Portfolio-Week-Project#119]
- [x] CSS: .post-comment-textarea -> add color: var(--text-color)
- [x] add aria-labels to buttons with emoji
- [x] need transparent logo 
- [x] add class .comment-bttn" to submit comment button, hot button, new button
- [x] "be first to comment" and actual comments needs var(--text-color)
- [x] none of the buttons accessing parent html for font styling 
- [x] giphy input box not reaching
- [x] submit comment input not reaching 
- [x] 'darkside', changename -> reply, submit -> post
- [x] placeholder "share your thoughts"
